@php
    $isCompleted = $eventType === 'maintenance_order.completed.v1';
    $vehicle = $order->vehicle;
    $owner = $vehicle?->owner;
    $workshop = $order->workshop;
    $vehicleName = trim(implode(' ', array_filter([$vehicle?->brand, $vehicle?->model])));
    $vehicleReference = $vehicleName !== ''
        ? $vehicleName.' ('.($vehicle?->license_plate ?? 'no plate').')'
        : ($vehicle?->license_plate ?? 'your vehicle');
    $workshopName = $workshop?->name ?? 'the assigned workshop';
    $workshopAddress = collect([$workshop?->address, $workshop?->city])->filter()->implode(', ');
@endphp

<p>
    Hi {{ $owner?->name ?? 'there' }},
</p>

@if ($isCompleted)
    <p>
        Your vehicle {{ $vehicleReference }} is ready for pickup.
    </p>

    <ul>
        <li>Pickup available from: {{ $order->finished_at?->format('Y-m-d H:i') ?? 'the completion time recorded in MaintOps' }}</li>
        <li>Workshop: {{ $workshopName }}</li>
        <li>Address: {{ $workshopAddress !== '' ? $workshopAddress : 'Address not available' }}</li>
    </ul>
@else
    <p>
        Your maintenance appointment for {{ $vehicleReference }} has been scheduled.
    </p>

    <ul>
        <li>Bring the vehicle on: {{ $order->scheduled_at?->format('Y-m-d H:i') ?? 'the scheduled date recorded in MaintOps' }}</li>
        <li>Workshop: {{ $workshopName }}</li>
        <li>Address: {{ $workshopAddress !== '' ? $workshopAddress : 'Address not available' }}</li>
    </ul>
@endif

<p>
    This email was generated by MaintOps for the maintenance order #{{ $order->id }}.
</p>
